#!/usr/bin/env bash
dir=$1
if [[ -d $dir ]]; then
	cd $dir
	wget -r -nd -np -l 1 -A Homo_sapiens.GRCh37.dna.chromosome.*.fa.gz ftp://ftp.ensembl.org/pub/grch37/current/fasta/homo_sapiens/dna/
	mv Homo_sapiens.GRCh37.dna.chromosome.MT.fa.gz Homo_sapiens.GRCh37.dna.chromosome.M.fa.gz
	rm -f hg19.fa
	for i in M {1..22} X Y; do
		echo ":INFO: extracting Homo_sapiens.GRCh37.dna.chromosome.$i.fa.gz"
		gunzip -c Homo_sapiens.GRCh37.dna.chromosome.$i.fa.gz | sed "s/>.*/>chr$i/" >> hg19.fa
	done
	wget ftp://ftp.ncbi.nih.gov/snp/organisms/human_9606_b149_GRCh37p13/VCF/GATK/common_all_20161121.vcf.gz
	echo ":INFO: extracting common_all_20161121.vcf.gz"
	gunzip -c common_all_20161121.vcf.gz > hg19.fa.vcf
	rm -f *.gz
else
	echo ":ERROR: no such directory $dir"
fi