#! /usr/bin/env bash
shopt -s expand_aliases
shopt -s extglob
# kill 0 only would a) kill also parent processes and b) infinit recursion leads to segmentation fault
trap "trap - SIGTERM && kill -PIPE -- -$$ &> /dev/null" INT TERM SIGINT SIGTERM EXIT
# set -e

usage() {
	echo "SYNOPSIS"
	echo $(basename $0)" -1 [PATH] -g [PATH] -o [PATH]"
	echo ""
	echo "DESCRIPTION"
	echo $(basename $0)" is a multiple variant caller and annotation pipeline for germline variants"
	echo "v0.1.5"
	echo ""
	echo "INSTALLATION"
	echo "-i       | --install [all|anno]  : installation into exported directory: export MUVAC=/full/path/to/tools"
	echo "-t       | --threads [value]     : threads - default: $threads"
	echo "-annovar | --annovar [url]       : annovar download url (see http://annovar.openbioinformatics.org/)"
	echo ""
	echo "OPTIONS"
	echo "-1 | --fastq1 [path,path,..]     : fastq input - single or first pair, comma seperated"
	echo "-2 | --fastq2 [path,path,..]     : fastq input - optional. second pair, comma seperated"
	echo "-g | --genome [path]             : genome fasta with suffig '.fa'"
	echo "-a | --adapter [string]          : adapter sequence"
	echo "-o | --out [path]                : output directory - default: $PWD/results"
	echo "-t | --threads [value]           : threads - default: $threads"
	echo "-l | --log [path]                : log file - default: $PWD/results/run.log "
	echo "-h | --help                      : prints this message"
	echo "-v | --verbose                   : enable verbose mode"
	echo "-r | --remove                    : finally remove intermediate results and temporary files"
	echo ""
	echo "-no-pre   | --no-preprocessing   : disables quality analysis, adapter clipping, error correction"
	echo "-no-trim  | --no-trimming        : disables quality trimming"
	echo "-no-bmap  | --no-bwa             : disables mapping by BWA"
	echo "-no-tmap  | --no-tophat          : disables mapping by TopHat2"
	echo "-no-smap  | --no-segemehl        : disables mapping by Segemehl"
	echo "-no-recal | --no-recalibration   : disables GATK best practice realignment and base recalibration"
	echo "-no-hc    | --no-haplotypecaller : disables variant caller GATK HaplotypeCaller"
	echo "-no-mu    | --no-mutect          : disables variant caller GATK MuTect2"
	echo "-no-fb    | --no-freebayes       : disables variant caller Freebayes"
	echo "-no-st    | --no-samtools        : disables variant caller Samtools/Bcftools"
	echo "-no-pp    | --no-platypus        : disables variant caller Platypus"
	echo "-no-anno  | --no-annotation      : disables variant annotation by Annovar and SnpEff"
	#echo "-split -Sq -Sa -Sconv -Str -Scor -Sms -Smt -Smb -Sort -Srg -Srmd -Sreo -Sret -Srea -Srec -Sprint -Shc -Smu -Sfb -Sst -Spp -Smerge -Savar -Snpeff"
	exit 0
}

installdependencies () {
	if [[ $(make -h &> /dev/null; echo $?) -gt 0 ]]; then
		echo ":ERROR: dependency missing: make"
		return 1
	fi
	if [[ $(cmake -h &> /dev/null; echo $?) -gt 0 ]]; then
		echo ":ERROR: dependency missing: cmake"
		return 1
	fi
	if [[ $(git --version &> /dev/null; echo $?) -gt 0 ]]; then
		echo ":ERROR: dependency missing: git"
		return 1
	fi
	if [[ $(g++ -v &> /dev/null; echo $?) -gt 0 ]]; then
		echo ":ERROR: dependency missing: g++"
		return 1
	fi
	if [[ $(gcc -v &> /dev/null; echo $?) -gt 0 ]]; then
		echo ":ERROR: dependency missing: gcc"
		return 1
	fi
	if [[ $(unzip -h &> /dev/null; echo $?) -gt 0 ]]; then
		echo ":ERROR: dependency missing: unzip"
		return 1
	fi
	if [[ $(python -c 'import Cython.Distutils'; echo $?) -gt 0 ]]; then
		echo ":ERROR: dependency missing: cython"
		return 1
	fi
}

rundependencies () {
    if [[ $(bash -version | head -1 | perl -lane 'if ($_=~/version\s+4\.(\d+)/){if($1>=3){print 1}else{print 0}}else{print 0}') -eq 0 ]]; then
        echo ":ERROR: dependency missing: bash 4.3"
        return 1
    fi
    if [[ ! -e /usr/include/python2.7/Python.h ]]; then
        echo ":ERROR: dependency missing: python-dev"
        return 1
    fi
    if [[ $(java -version 2>&1 | head -1 | grep -c '1.8') -ne 1 ]]; then
        echo ":ERROR: dependency missing: java 8"
        return 1
    fi
}

install () {
	if [[ $make == "all" ]]; then
		cp $muvacdir/muvac $tooldir
		cp $muvacdir/dlh19 $tooldir
		cp $muvacdir/vcfmerge.pl $tooldir
		cp $muvacdir/vcfix.pl $tooldir
	fi

	if [[ $make == "all" ]]; then
		echo ":INFO: installing ncurses"
		url='https://ftp.gnu.org/pub/gnu/ncurses/ncurses-6.0.tar.gz'
		wget -q $url -O $tooldir/ncurses.tar.gz && tar -xzf $tooldir/ncurses.tar.gz -C $tooldir && rm $tooldir/ncurses.tar.gz
		ncurses=$(ls -dv $tooldir/ncurses-*/ | tail -1)
		cd $ncurses
		rm -rf built; mkdir built 
		make clean; ./configure --prefix=$PWD/built && make && make install
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: ncurses installation failed"
			return 1
		fi

		echo  ":INFO: installing gtextutils"
		url='https://github.com/agordon/libgtextutils/releases/download/0.7/libgtextutils-0.7.tar.gz'
		wget -q $url -O $tooldir/libgtextutils.tar.gz && tar -xzf $tooldir/libgtextutils.tar.gz -C $tooldir && rm $tooldir/libgtextutils.tar.gz
		gtextutils=$(ls -dv $tooldir/libgtextutils-*/ | tail -1)
		cd $gtextutils
		rm -rf built; mkdir built 
		make clean; ./configure --prefix=$PWD/built && sed -i -r 's/^\s*CXXFLAGS\s*=\s*/override CXXFLAGS += /' Makefile && make CXXFLAGS="-std=c++03" && make install
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: gtextutils installation failed"
			return 1
		fi

		echo ":INFO: installing zlib"
		url='https://github.com/madler/zlib/archive/v1.2.8.tar.gz' #current version 1.2.11 is not recognized as bigger than 1.2.5 by R
		wget -q $url -O $tooldir/zlib.tar.gz && tar -xzf $tooldir/zlib.tar.gz -C $tooldir && rm $tooldir/zlib.tar.gz
		zlib=$(ls -dv $tooldir/zlib-*/ | tail -1)
		cd $zlib 
		rm -rf built; mkdir built 
		make clean; ./configure --prefix=$PWD/built && make && make install
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: zlib installation failed"
			return 1
		fi
	fi
	ncurses=$(ls -dv $tooldir/ncurses-*/ | tail -1)
	gtextutils=$(ls -dv $tooldir/libgtextutils-*/ | tail -1)
	zlib=$(ls -dv $tooldir/zlib-*/ | tail -1)

	if [[ $make == "all" ]] || [[ $make == "bcftools" ]]; then
		echo ":INFO: installing bcftools"
		url='https://github.com/samtools/bcftools/releases/download/1.3.1/bcftools-1.3.1.tar.bz2'
		wget -q $url -O $tooldir/bcftools.tar.bz2 && tar -xjf $tooldir/bcftools.tar.bz2 -C $tooldir && rm $tooldir/bcftools.tar.bz2
		cd $(ls -dv $tooldir/bcftools-*/ | tail -1)
		make clean;
		make
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: bcftools installation failed"
			return 1
	    fi
	fi

	if [[ $make == "all" ]] || [[ $make == "freebayes" ]]; then
		echo ":INFO: installing freebayes"
		cd $tooldir
		git clone --recursive git://github.com/ekg/freebayes.git
		cd freebayes
		make clean
		rm -rf bamtools
		git clone https://github.com/pezmaster31/bamtools.git
		cd bamtools
		rm -rf build; mkdir -p build
		cd build
		cmake .. && make
		cd $tooldir/freebayes/vcflibs
		make clean; make
		cd $tooldir/freebayes/SeqLib
		make clean; ./configure --prefix=$PWD && make && make install
		cd $tooldir/freebayes
		make
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: freebayes installation failed"
			return 1
		fi
	fi

	if [[ $make == "all" ]] || [[ $make == "fastqc" ]]; then
		echo ":INFO: installing fastqc"
		url='http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.5.zip'
		wget -q $url -O $tooldir/fastqc.zip && unzip -q -o -d $tooldir $tooldir/fastqc.zip && rm $tooldir/fastqc.zip
		chmod 755 $tooldir/FastQC/fastqc
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: fastqc installation failed"
			return 1
		fi
		mv $tooldir/FastQC $tooldir/$($tooldir/FastQC/fastqc -v | sed 's/ /-/g')
	fi

	if [[ $make == "all" ]] || [[ $make == "trimmomatic" ]]; then
		echo ":INFO: installing trimmomatic"
		url='http://www.usadellab.org/cms/uploads/supplementary/Trimmomatic/Trimmomatic-0.36.zip'
		wget -q $url -O $tooldir/trimmomatic.zip && unzip -q -o -d $tooldir $tooldir/trimmomatic.zip && rm $tooldir/trimmomatic.zip
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: trimmomatic installation failed"
			return 1
		fi
	fi

	if [[ $make == "all" ]] || [[ $make == "dnapi" ]]; then
		echo ":INFO: installing dnapi"
		url='https://github.com/jnktsj/DNApi/archive/v1.1.tar.gz'
		wget -q $url -O $tooldir/dnapi.tar.gz && tar -xzf $tooldir/dnapi.tar.gz -C $tooldir && rm $tooldir/dnapi.tar.gz
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: dnapi installation failed"
			return 1
		fi
	fi

	if [[ $make == "all" ]] || [[ $make == "fastx_toolkit" ]]; then
		echo ":INFO: installing fastx_toolkit"
		url='https://github.com/agordon/fastx_toolkit/releases/download/0.0.14/fastx_toolkit-0.0.14.tar.bz2'
		wget -q $url -O $tooldir/fastx_toolkit.tar.bz2 && tar -xjf $tooldir/fastx_toolkit.tar.bz2 -C $tooldir && rm $tooldir/fastx_toolkit.tar.bz2
		cd $(ls -dv $tooldir/fastx_toolkit-*/ | tail -1)
		rm -rf built; mkdir built 
		export GTEXTUTILS_CFLAGS="-I$gtextutils/built/include/gtextutils/gtextutils -I$gtextutils/libgtextutils-0.7/built/include/gtextutils -I$gtextutils/built/include"
		export GTEXTUTILS_LIBS="-L$gtextutils/built/lib"
		make clean; ./configure --prefix=$PWD/built 		
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: fastx_toolkit installation failed"
			return 1
		fi
		make -i && make install -i
		if [[ ! -e built/bin/fastx_clipper ]]; then
			echo ":ERROR: fastx_toolkit installation failed"
			return 1
		fi
	fi

	if [[ $make == "all" ]] || [[ $make == "cutadapt" ]]; then
		echo ":INFO: installing cutadapt"
		mkdir -p $tooldir/cutadapt
		cd $tooldir/cutadapt
		export PYTHONUSERBASE=$tooldir/cutadapt
		unset PYTHONPATH
		wget -q https://bootstrap.pypa.io/get-pip.py -O get-pip.py && python get-pip.py --user
		bin/pip install --user cutadapt
	fi

	if [[ $make == "all" ]] || [[ $make == "gatk" ]]; then
		echo ":INFO: installing gatk"
		url='http://mirrors.ae-online.de/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz'
		wget -q $url -O $tooldir/maven.tar.gz && tar -xzf $tooldir/maven.tar.gz -C $tooldir && rm $tooldir/maven.tar.gz
		maven=$(ls $tooldir/apache-maven-*/bin/mvn | sort -r | head -1)
		url='https://github.com/broadgsa/gatk-protected/archive/3.7.tar.gz'
		wget -q $url -O $tooldir/gatk.tar.gz && tar -xzf $tooldir/gatk.tar.gz -C $tooldir && rm $tooldir/gatk.tar.gz
		cd $(ls -dv $tooldir/gatk-*/ | tail -1)
		$maven clean; $maven -T $threads verify
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: gatk installation failed"
			return 1
		fi
	fi

	if [[ $make == "all" ]] || [[ $make == "tophat" ]]; then
		echo ":INFO: installing bowtie2"
		url='https://sourceforge.net/projects/bowtie-bio/files/bowtie2/2.3.0/bowtie2-2.3.0-source.zip'
		wget -q $url -O $tooldir/bowtie2.zip && unzip -q -o -d $tooldir $tooldir/bowtie2.zip && rm $tooldir/bowtie2.zip
		cd $(ls -dv $tooldir/bowtie2-*/ | tail -1)
		make NO_TBB=1
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: bowtie2 installation for tophat2 failed"
			return 1
		fi
		echo ":INFO: installing tophat2"
		url='https://ccb.jhu.edu/software/tophat/downloads/tophat-2.1.1.Linux_x86_64.tar.gz'
		wget -q $url -O $tooldir/tophat2.tar.gz && tar -xzf $tooldir/tophat2.tar.gz -C $tooldir && rm $tooldir/tophat2.tar.gz
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: tophat2 installation failed"
			return 1
		fi
	fi

	if [[ $make == "all" ]] || [[ $make == "bwa" ]]; then
		echo ":INFO: installing bwa"
		url='https://github.com/lh3/bwa/releases/download/v0.7.15/bwa-0.7.15.tar.bz2'
		wget -q $url -O $tooldir/bwa.tar.bz2 && tar -xjf $tooldir/bwa.tar.bz2 -C $tooldir && rm $tooldir/bwa.tar.bz2
		cd $(ls -dv $tooldir/bwa-*/ | tail -1)
		make clean; sed -i -r 's/^\s*CFLAGS\s*=\s*/override CFLAGS += /' Makefile && make CFLAGS="-I$zlib/built/include/ -L$zlib/built/lib"
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: bwa installation failed"
			return 1
		fi
	fi

	if [[ $make == "all" ]] || [[ $make == "segemehl" ]]; then
		echo ":INFO: installing segemehl"
		# url='http://www.bioinf.uni-leipzig.de/Software/segemehl/segemehl_0_2_0.tar.gz'
		# wget -q $url -O $tooldir/segemehl.tar.gz && tar -xzf $tooldir/segemehl.tar.gz -C $tooldir && rm $tooldir/segemehl.tar.gz
		cp -r $muvacdir/segemehl_0_3_0 $tooldir
		cd $(ls -dv $tooldir/segemehl_*/ | tail -1)
		sed -i -r 's/^\s*(C|LD)FLAGS\s*=\s*/override \1FLAGS += /' Makefile
		make clean; make CFLAGS="-I$ncurses/built/include -I$ncurses/built/include/ncurses -I$zlib/built/include" LDFLAGS="-L$ncurses/built/lib -L$zlib/built/lib"
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: segemehl installation failed"
			return 1
		fi
	fi

	if [[ $make == "all" ]] || [[ $make == "samtools" ]]; then
		echo ":INFO: installing samtools"
		url='https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2'
		wget -q $url -O $tooldir/samtools.tar.bz2 && tar -xjf $tooldir/samtools.tar.bz2 -C $tooldir && rm $tooldir/samtools.tar.bz2
		cd $(ls -dv $tooldir/samtools-*/ | tail -1)
		rm -rf built; mkdir built
		make clean; ./configure --prefix=$PWD/built CFLAGS="-I$ncurses/built/include -I$ncurses/built/include/ncurses -I$zlib/built/include" LDFLAGS="-L$ncurses/built/lib -L$zlib/built/lib" && sed -i -r 's/^\s*(C|LD)FLAGS\s*=\s*/override \1FLAGS += /' Makefile &&  make CFLAGS="-fPIC -I$ncurses/built/include -I$ncurses/built/include/ncurses -I$zlib/built/include" LDFLAGS="-L$ncurses/built/lib -L$zlib/built/lib" && make install
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: samtools installation failed"
			return 1
		fi
		cd $(ls -dv htslib-*/ | tail -1)
		make && make install
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: htslib installation failed"
			return 1
		fi
	fi
	samtools=$(ls -dv $tooldir/samtools-*/ | tail -1)

	if [[ $make == "all" ]] || [[ $make == "platypus" ]]; then
		echo ":INFO: installing platypus"
		cd $tooldir
		git clone https://github.com/andyrimmer/Platypus.git
		cd Platypus
		make clean
		export C_INCLUDE_PATH=$samtools/built/include
		export LIBRARY_PATH=$samtools/built/lib
		export LD_LIBRARY_PATH=$samtools/built/lib
		make PREFIX=$PWD && chmod 755 bin/Platypus.py
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: platypus installation failed"
			return 1
		fi
	fi

	if [[ $make == "all" ]] || [[ $make == "rcorrector" ]]; then 
		echo ":INFO: installing rcorrector"
		url=https://github.com/mourisl/Rcorrector/archive/v1.0.2.tar.gz
		wget -q $url -O $tooldir/rcorrector.tar.gz && tar -xzf $tooldir/rcorrector.tar.gz -C $tooldir && rm $tooldir/rcorrector.tar.gz
		cd $(ls -dv $tooldir/Rcorrector-*/ | tail -1)
		url=https://github.com/gmarcais/Jellyfish/releases/download/v2.2.4/jellyfish-2.2.4.tar.gz
		wget -q $url -O jellyfish.tar.gz
		sed -i '/wget/d' Makefile		
		make clean; make
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: rcorrector installation failed"
			return 1
		fi
		chmod 755 run_rcorrector.pl
	fi

	if [[ $make == "all" ]] || [[ $make == "picard" ]]; then
		echo ":INFO: installing picard"
		mkdir -p $tooldir/picard-2.8.2
		url='https://github.com/broadinstitute/picard/releases/download/2.8.2/picard-2.8.2.jar'
		wget -q $url -O $tooldir/picard-2.8.2/picard.jar
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: picard installation failed"
			return 1
		fi
	fi

	# if [[ $make == "annotation" ]] || [[ $make == "polyphen" ]] && [[ $noanno -eq 0 ]]; then
	# 	echo ":INFO: installing perl modules for polyphen"
	# 	wget cpanmin.us -O $tooldir/cpanm
	# 	chmod 755 $tooldir/cpanm
	# 	$tooldir/cpanm -f -l $tooldir/perl5 XML::Simple LWP::Simple DBD::SQLite CGI
	# 	export PERL5LIB=$tooldir/perl5/lib/perl5
	# 	url='http://genetics.bwh.harvard.edu/pph2/dokuwiki/_media/polyphen-2.2.2r405c.tar.gz'
	# 	wget $url -O $tooldir/polyphen.tar.gz && tar -xzf $tooldir/polyphen.tar.gz -C $tooldir && rm $tooldir/polyphen.tar.gz

	# 	export PPH=$(ls -d $tooldir/polyphen-*/ | sort -r | head -1)

	# 	url=$(wget --spider --force-html -r -nd -np -l 1 -A *x64-linux.tar.gz ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/ 2>&1 | grep '^--.*tar.gz' | awk '{print $NF}')
	# 	wget $url -O $tooldir/blast.tar.gz && tar -xzf $tooldir/blast.tar.gz -C $tooldir && rm $tooldir/blast.tar.gz
	# 	rm -rf $PPH/blast
	# 	mv $(ls -d $tooldir/ncbi-blast-*/ | sort -r | head -1) $PPH/blast

	# 	echo ":INFO: installing ucsc kent user utilities for polyphen"
	# 	url='http://hgdownload.cse.ucsc.edu/admin/exe/userApps.src.tgz'
	# 	wget $url -O $tooldir/kent.tgz && tar -xzf $tooldir/kent.tgz -C $tooldir && rm $tooldir/kent.tgz
	# 	cd $tooldir/userApps/kent/src/lib && make 
	# 	cd $tooldir/userApps/kent/src/utils/faSplit && make BINDIR=$PPH/bin
	# 	if [[ $? -gt 0 ]]; then
	# 		echo ":ERROR: ucsc kent user utilities installation failed"
	# 		return 1
	# 	fi
	# 	cd $tooldir/userApps/kent/src/blat && make BINDIR=$PPH/bin
	# 	if [[ $? -gt 0 ]]; then
	# 		echo ":ERROR: ucsc kent user utilities installation failed"
	# 		return 1
	# 	fi
	# 	cd $tooldir/userApps/kent/src/utils/twoBitToFa && make BINDIR=$PPH/bin
	# 	if [[ $? -gt 0 ]]; then
	# 		echo ":ERROR: ucsc kent user utilities installation failed"
	# 		return 1
	# 	fi

	# 	echo ":INFO: installing polyphen databases - needs ~200gb disk space and runs several hours/days"
	# 	cd $PPH/nrdb
	# 	wget ftp://ftp.expasy.org/databases/uniprot/current_release/uniref/uniref100/uniref100.fasta.gz
	# 	gunzip uniref100.fasta.gz
	# 	$PPH/update/format_defline.pl uniref100.fasta > uniref100-formatted.fasta
	# 	perl -lane 'next unless $_=~/^>/; $F[0]=~/([^>|]+)$/; print $1."\t".(join(" ",grep {$_!~/=/} @F[1..$#F]) || ".")' uniref100-formatted.fasta > uniref100ToGeneName.txt
	# 	# $PPH/blast/bin/makeblastdb -in uniref100-formatted.fasta -dbtype prot -out uniref100 -parse_seqids
	# 	# rm -f uniref100.fasta uniref100-formatted.fasta
	# 	# divided by max integer range, else faSplit produces billions of files
	# 	chunks=$(du -b uniref100-formatted.fasta | awk -v t=$threads '{min=sprintf("%d",$1/2147483648); min=min+1; if(t<min){t=min} printf("%d",$1/(t+t*0.34))}')
	# 	$PPH/bin/faSplit about uniref100-formatted.fasta $chunks $PWD/
	# 	for i in $(ls *.fa | grep -v uniref); do 
	# 		echo "$PPH/nrdb/blast/bin/makeblastdb -in $i -dbtype prot -parse_seqids"
	# 	done | xargs -P $threads -I {} bash -c {}
	# 	$PPH/nrdb/blast/bin/blastdb_aliastool -dblist "$(ls *.fa | grep -v uniref | xargs -echo)" -dbtype prot -out uniref100 -title uniref100
		
	# 	cd $PPH/wwpdb/divided/pdb/
	# 	wget -q -r -np -nH -nc --cut-dirs=7 ftp://ftp.ebi.ac.uk/pub/databases/pdb/data/structures/divided/pdb		
	# 	cd $PPH/wwpdb/all/pdb/
	# 	for i in $PPH/wwpdb/divided/pdb/*/*; do
	# 		ln -f -s $i $PWD/$(basename $i)
	# 	done

	# 	cd $PPH/dssp
	# 	wget -q -r -np -nd ftp://ftp.cmbi.ru.nl/pub/molbio/data/dssp

	# 	url='ftp://genetics.bwh.harvard.edu/pph2/bundled/polyphen-2.2.2-databases-2011_12.tar.bz2'
	# 	wget $url -O $tooldir/polyphenDB.tar.gz && tar -xzf $tooldir/polyphenDB.tar.gz -C $tooldir && rm $tooldir/polyphenDB.tar.gz
	# 	url='ftp://genetics.bwh.harvard.edu/pph2/bundled/polyphen-2.2.2-alignments-mlc-2011_12.tar.bz2'
	# 	wget $url -O $tooldir/polyphenMLC.tar.gz && tar -xzf $tooldir/polyphenMLC.tar.gz -C $tooldir && rm $tooldir/polyphenMLC.tar.gz
	# 	url='ftp://genetics.bwh.harvard.edu/pph2/bundled/polyphen-2.2.2-alignments-multiz-2009_10.tar.bz2'
	# 	wget $url -O $tooldir/polyphenMZ.tar.gz && tar -xzf $tooldir/polyphenMZ.tar.gz -C $tooldir && rm $tooldir/polyphenMZ.tar.gz

	# 	echo ":INFO: installing polyphen"
	# 	url='https://sourceforge.net/projects/weka/files/weka-3-6/3.6.15/weka-3-6-15.zip'
	# 	wget $url -O $PPH/weka.zip && unzip -q -o -d $PPH $PPH/weka.zip && rm $PPH/weka.zip
	# 	mv $(ls -d $PPH/weka-* | sort -r | head -1) $PPH/weka
	# 	url='http://mafft.cbrc.jp/alignment/software/mafft-7.310-without-extensions-src.tgz'
	# 	wget $url -O $PPH/src/mafft.tgz && tar -xzf $PPH/src/mafft.tgz -C $PPH/src/ && rm $PPH/src/mafft.tgz
	# 	mv $(ls -d $PPH/src/mafft-* | sort -r | head -1) $PPH/src/mafft

	# 	cd $PPH/src
	# 	make clean; make download && make && make install
	# 	if [[ $? -gt 0 ]]; then
	# 		echo ":ERROR: polyphen installation failed"
	# 		return 1
	# 	fi
	# 	cd $PPH
	# 	(echo Y; echo Y; echo Y; echo n; echo '/tmp'; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y; echo Y) | ./configure		
	# fi

	if [[ $make == "anno" ]] || [[ $make == "annovar" ]] && [[ $annovar ]] && [[ $noanno -eq 0 ]]; then
		echo ":INFO: installing annovar - needs ~70gb disk space"
		url=$annovar
		wget $url -O $tooldir/annovar.tar.gz && tar -xzf $tooldir/annovar.tar.gz -C $tooldir && rm $tooldir/annovar.tar.gz
		wget http://www.openbioinformatics.org/annovar/download/table_annovar.pl -O $tooldir/annovar/table_annovar.pl && chmod 755 $tooldir/annovar/table_annovar.pl
		cd $tooldir/annovar
		./annotate_variation.pl -buildver hg19 -downdb -webfrom annovar refGene humandb/ #refSeq
		# ./annotate_variation.pl -buildver hg19 -downdb ensGene humandb/ #UCSC - needs seq to get mRNA
		# ./annotate_variation.pl -buildver hg19 -downdb knownGene humandb/ #UCSC - needs seq to get mRNA
		# ./annotate_variation.pl -buildver hg19 -downdb seq humandb/hg19_seq
		# ./retrieve_seq_from_fasta.pl humandb/hg19_ensGene.txt -seqdir humandb/hg19_seq -format ensGene -outfile humandb/hg19_ensGeneMrna.fa
		# ./retrieve_seq_from_fasta.pl humandb/hg19_knownGene.txt -seqdir humandb/hg19_seq -format knownGene -outfile humandb/hg19_knownGeneMrna.fa
		wget http://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/ensemblToGeneName.txt.gz -O humandb/ensemblToGeneName.txt.gz && gunzip humandb/ensemblToGeneName.txt.gz
		# ./annotate_variation.pl -buildver hg19 -downdb cytoBand humandb/
		# ./annotate_variation.pl -buildver hg19 -downdb genomicSuperDups humandb/ 
		./annotate_variation.pl -buildver hg19 -downdb -webfrom annovar esp6500siv2_all humandb/
		./annotate_variation.pl -buildver hg19 -downdb -webfrom annovar 1000g2015aug humandb/
		./annotate_variation.pl -buildver hg19 -downdb -webfrom annovar exac03 humandb/ 
		./annotate_variation.pl -buildver hg19 -downdb -webfrom annovar avsnp147 humandb/ 
		./annotate_variation.pl -buildver hg19 -downdb -webfrom annovar dbnsfp33a humandb/
		# ./annotate_variation.pl -buildver hg19 -downdb -webfrom annovar snp142 humandb
		./annotate_variation.pl -buildver hg19 -downdb tfbsConsSites humandb/
		./annotate_variation.pl -buildver hg19 -downdb targetScanS humandb/
		./annotate_variation.pl -buildver hg19 -downdb wgRna humandb/
		./annotate_variation.pl -buildver hg19 -downdb gwasCatalog humandb/
		./annotate_variation.pl -buildver hg19 -downdb -webfrom annovar clinvar_20170130 humandb/
	fi

	if [[ $make == "anno" ]] || [[ $make == "snpeff" ]] && [[ $noanno -eq 0 ]]; then
		echo ":INFO: installing snpeff - needs ~110gb disk space"
		url='http://sourceforge.net/projects/snpeff/files/snpEff_latest_core.zip'
		wget $url -O $tooldir/snpeff.zip && unzip -q -o -d $tooldir $tooldir/snpeff.zip && rm $tooldir/snpeff.zip
		cd $tooldir/snpEff
		java -jar snpEff.jar download -v GRCh37.75
		#java -jar snpEff.jar download -v hg19 #hg19: UCSC, hg19kg: UCSC knownGenes, GRCh37.75: Ensembl 
		url='http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/integration_data_jan2011/byDataType/openchrom/jan2011/promoter_predictions/master_known.bed'
		wget $url -O data/promoter.bed
		url='http://ftp.ebi.ac.uk/pub/databases/ensembl/encode/integration_data_jan2011/byDataType/openchrom/jan2011/mirna_tss/miRNA_promoters_hg19_edited_data.bed'
		wget $url -O data/miRNApromoter.bed
		url='ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/clinvar.vcf.gz'
		wget $url -O data/clinvar.vcf.gz
		url='ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/clinvar.vcf.gz.tbi'
		wget $url -O data/clinvar.vcf.gz.tbi
		url='ftp://ftp.broadinstitute.org/pub/ExAC_release/release1/ExAC.r1.sites.vep.vcf.gz'
		wget $url -O data/exac.vcf.gz
		url='ftp://ftp.broadinstitute.org/pub/ExAC_release/release1/ExAC.r1.sites.vep.vcf.gz.tbi'
		wget $url -O data/exac.vcf.gz.tbi
		
		# url='https://drive.google.com/open?id=0B60wROKy6OqceTNZRkZnaERWREk'
		#(see https://sites.google.com/site/jpopgen/dbNSFP)
		url='ftp://dbnsfp:dbnsfp@dbnsfp.softgenetics.com/dbNSFPv2.9.3.zip'
		wget $url -O data/dbnsfp.zip && unzip -q -o -d data dbnsfp.zip && rm data/dbnsfp.zip
		head -n 1 data/dbNSFP*_variant.chr1 > data/dbNSFP.txt
		cat dbNSFP*_variant.chr* | grep -v "^#" >> data/dbNSFP.txt
		rm dbNSFP*_variant.chr*
		$samtools/built/bin/bgzip -f -@ $threads < data/dbNSFP.txt > data/dbNSFP.txt.gz
		$samtools/built/bin/tabix -f -s 1 -b 2 -e 2 data/dbNSFP.txt.gz
		
		# url='http://www.genome.gov/admin/gwascatalog.txt'
		url='ftp://ftp.ebi.ac.uk/pub/databases/gwas/releases/latest/gwas-catalog-associations.tsv'
		wget $url -O data/gwas.txt
	fi

	echo ":INFO: installation successful"
	sleep 1
	return 0
}

progress () {
	mod=0
	while true; do
		mod=$((mod+1))
		if [[ $mod -eq 2 ]]; then
			mod=0
			echo -en "\r/"
		else
			echo -en "\r\\"
		fi
		sleep 1
	done
}

userlog () {
	tail -f $1 2>&1 | grep -E --line-buffered '^\s*(:INFO|:ERROR|Elapsed \(wall|Maximum resident)'
}

pipeline () {
if [[ $noprep -eq 0 ]]; then
	echo ":INFO: calcultating qualities"
	mkdir -p $outdir/qualities
	cmd=()
	for f in {${fastq1[@]},${fastq2[@]}}; do
		cmd+=("${BASH_ALIASES[fastqc]} -outdir $outdir/qualities $f\n")
	done 
	#enable dev skip option if already done
	[[ $Sq -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}

	if [[ $adapter ]]; then
		echo ":INFO: clipping"
		mkdir -p $outdir/clipped
		cmd=()
		if [[ ${fastq2[0]} ]]; then
			for i in $(seq 0 $((${#fastq1[@]}-1))); do
				o1=$outdir/clipped/$(basename ${fastq1[$i]})
				o2=$outdir/clipped/$(basename ${fastq2[$i]})
				cmd+=("${BASH_ALIASES[cutadapt]} -b $adapter -B $adapter -m 12 -o $o1 -p $o2 ${fastq1[$i]} ${fastq2[$i]}\n")
				fastq1[$i]=$o1
				fastq2[$i]=$o2
			done 
		else 
			for i in $(seq 0 $((${#fastq1[@]}-1))); do
				o=$outdir/trimmed/$(basename ${fastq1[$i]})
				cmd+=("${BASH_ALIASES[cutadapt]} -b $adapter -m 12 -o ${fastq1[$i]}\n")
				fastq1[$i]=$o
			done 
		fi
		#enable dev skip option if already done
		[[ $Sa -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: clipping failed"
			return 1
		fi
	fi
fi

if [[ $Sconv -eq 0 ]]; then
	phred=$(head -400 ${fastq1[0]} | awk '{if(NR%4==0) printf("%s",$0);}' | od -A n -t u1 | awk 'BEGIN{min=100;max=0;}{for(i=1;i<=NF;i++) {if($i>max) max=$i; if($i<min) min=$i;}}END{if(max<=74 && min<59) print "phred33"; else if(max>73 && min>=64) print "phred64"; else if(min>=59 && min<64 && max>73) print "solexa64"; else print "unknown";}')
	if [[ ! $phred =~ ^phred ]]; then
		echo ":ERROR: $phred fastq encoding - need sanger (phred33) or illumina (phred64)"
		return 1
	fi
	if [[ $phred == "phred64" ]]; then
		echo ":INFO: converting quality scores"
		mkdir -p $outdir/converted
		cmd=()
		for i in $(seq 0 $((${#fastq1[@]}-1))); do
			o=$outdir/converted/$(basename ${fastq1[$i]})
			cmd+=("${BASH_ALIASES[fastq_quality_converter]} -i $f -o $o\n")
			fastq1[$i]=$o
		done 
		for i in $(seq 0 $((${#fastq2[@]}-1))); do
			o=$outdir/converted/$(basename ${fastq2[$i]})
			cmd+=("${BASH_ALIASES[fastq_quality_converter]} -i $f -o $o\n")
			fastq2[$i]=$o
		done 
		#enable dev skip option if already done
		echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {}
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: quality reencoding failed"
			return 1
		fi
	fi
fi

if [[ $notrim -eq 0 ]]; then
	echo ":INFO: trimming"
	mkdir -p $outdir/trimmed
	cmd=()
	if [[ ${fastq2[0]} ]]; then
		for i in $(seq 0 $((${#fastq1[@]}-1))); do
			o1=$outdir/trimmed/$(basename ${fastq1[$i]})
			o2=$outdir/trimmed/$(basename ${fastq2[$i]})
			cmd+=("${BASH_ALIASES[trimmomatic]} PE -threads $threads -phred33 -trimlog $o1.log ${fastq1[$i]} ${fastq2[$i]} $o1 $o1.singletons $o2 $o2.singletons SLIDINGWINDOW:7:20 MINLEN:20\n")
			fastq1[$i]=$o1
			fastq2[$i]=$o2
		done
	else 
		for i in $(seq 0 $((${#fastq1[@]}-1))); do
			o=$outdir/trimmed/$(basename ${fastq1[$i]})
			cmd+=("${BASH_ALIASES[trimmomatic]} SE -threads $threads -phred33 -trimlog $o.log ${fastq1[$i]} $o SLIDINGWINDOW:7:20 MINLEN:20\n")
			fastq1[$i]=$o
		done
	fi
	#enable dev skip option if already done
	[[ $Str -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P 1 -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: trimming failed"
		return 1
	fi
fi

if [[ $noprep -eq 0 ]]; then
	echo ":INFO: read error correction"
	mkdir -p $outdir/rawcorrected
	if [[ ${fastq2[0]} ]]; then
		for i in $(seq 0 $((${#fastq1[@]}-1))); do
			o1=$outdir/rawcorrected/$(basename ${fastq1[$i]})
			o2=$outdir/rawcorrected/$(basename ${fastq2[$i]})
			if [[ $Scor -eq 0 ]]; then #enable dev skip option if already done
				/usr/bin/time -v ${BASH_ALIASES[rcorrector]} -1 ${fastq1[$i]} -2 ${fastq2[$i]} -od $outdir/rawcorrected -t $threads
				if [[ $? -gt 0 ]]; then
					echo ":ERROR: read error correction failed"
					return 1
				fi
				mv ${o1%.*}.cor.fq $o1
				mv ${o2%.*}.cor.fq $o2
			fi
			fastq1[$i]=$o1
			fastq2[$i]=$o2
		done
	else
		for i in $(seq 0 $((${#fastq1[@]}-1))); do
			o=$outdir/rawcorrected/$(basename ${fastq1[$i]})
			if [[ $Scor -eq 0 ]]; then #enable dev skip option if already done
				/usr/bin/time -v ${BASH_ALIASES[rcorrector]} -s ${fastq1[$i]} -od $outdir/rawcorrected -t $threads
				if [[ $? -gt 0 ]]; then
					echo ":ERROR: read error correction failed"
					return 1
				fi
				mv ${o%.*}.cor.fq $o
			fi
			fastq1[$i]=$o
		done
	fi
fi

	mapper=()
	segemehl=()
	bwa=()
	tophat=()
if [[ $nosmap -eq 0 ]]; then
	echo ":INFO: mapping - segemehl"
	mkdir -p $outdir/mapped/segemehl
	mapper+=(segemehl)
	cmd=()
	if [[ ! -e $genome.segemehl.idx ]]; then
		[[ $Sms -eq 0 ]] && /usr/bin/time -v ${BASH_ALIASES[segemehl]} -x $genome.segemehl.idx -d $genome || echo "${BASH_ALIASES[segemehl]} -x $genome.segemehl.idx -d $genome"
	fi
	for i in $(seq 0 $((${#fastq1[@]}-1))); do
		o=$outdir/mapped/segemehl/$(basename ${fastq1[$i]})
		o=${o%.*}
		if [[ $split -eq 0 ]]; then
			sege="${BASH_ALIASES[segemehl]}"
		else 
			sege="${BASH_ALIASES[segemehl]} -S --maxsplitevalue 30000"
		fi
		if [[ ${fastq2[0]} ]]; then
		 	cmd+=("$sege -i $genome.segemehl.idx -d $genome -q ${fastq1[$i]} -p ${fastq2[$i]} -A 95 -t $threads -u $o.unmapped.sam > $o.sam\n")
		else
			cmd+=("$sege -i $genome.segemehlidx -d $genome -q ${fastq1[$i]} -A 95 -t $threads -u $o.unmappes.sam > $o.sam\n")
		fi
		segemehl+=($o)
	done
	#enable dev skip option if already done
	[[ $Sms -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P 1 -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: segemehl mapping failed"
		return 1
	fi
fi

if [[ $nobmap -eq 0 ]]; then
	echo ":INFO: mapping - bwa"
	mkdir -p $outdir/mapped/bwa
	mapper+=(bwa)
	cmd=()
	if [[ ! -e $genome.pac ]]; then 
		[[ $Smb -eq 0 ]] && /usr/bin/time -v ${BASH_ALIASES[bwa]} index -a bwtsw $genome || echo "${BASH_ALIASES[bwa]} index -a bwtsw $genome"
	fi
	readlength=$(head -400 ${fastq1[0]} | awk 'NR%4==2{l+=length($0)}END{printf("%d",l/(NR/4))}')
	if [[ $readlength -lt 70 ]]; then 
		for f in {${fastq1[@]},${fastq2[@]}}; do
			o=$outdir/mapped/bwa/$(basename $f)
			o=${o%.*}
			cmd+=("${BASH_ALIASES[bwa]} aln -t $threads $genome $f > $o.sai\n")
		done
		for i in $(seq 0 $((${#fastq1[@]}-1))); do
			o1=$outdir/mapped/bwa/$(basename ${fastq1[$i]})
			o1=${o1%.*}	
			o2=$outdir/mapped/bwa/$(basename ${fastq2[$i]})
			o2=${o2%.*}
			if [[ ${fastq2[0]} ]]; then
				cmd+=("${BASH_ALIASES[bwa]} sampe $genome $o1.sai $o2.sai ${fastq1[$i]} ${fastq2[$i]} > $o1.all\n")
			else 
				cmd+=("${BASH_ALIASES[bwa]} samse $genome $o1.sai ${fastq1[$i]} > $o1.all\n")
			fi
			bwa+=($o1.all)
		done
	else 
		for i in $(seq 0 $((${#fastq1[@]}-1))); do
			o=$outdir/mapped/bwa/$(basename ${fastq1[$i]})
			o=${o%.*}	
			if [[ ${fastq2[0]} ]]; then
				cmd+=("${BASH_ALIASES[bwa]} mem -M -t $threads $genome ${fastq1[$i]} ${fastq2[$i]} > $o.all\n")
			else 
				cmd+=("${BASH_ALIASES[bwa]} mem -M -t $threads $genome ${fastq1[$i]} > $o.all\n")
			fi
			bwa+=($o.all)
		done
	fi
	#enable dev skip option if already done
	[[ $Smb -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P 1 -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: bwa mapping failed"
		return 1
	fi
	cmd=()
	for i in $(seq 0 $((${#bwa[@]}-1))); do
		o=${bwa[$i]}
		o=${o%.*}
		cmd+=("${BASH_ALIASES[samtools]} view -H $o.all > $o.sam && ${BASH_ALIASES[samtools]} view -F 4 $o.all >> $o.sam\n")
		cmd+=("${BASH_ALIASES[samtools]} view -H $o.all > $o.unmapped.sam && ${BASH_ALIASES[samtools]} view -f 4 $o.all >> $o.unmapped.sam\n")
		bwa[$i]=$o.sam
	done
	#enable dev skip option if already done
	[[ $Smb -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: bwa unmapped read extraction failed"
		return 1
	fi
fi

if [[ $notmap -eq 0 ]]; then
	echo ":INFO: mapping - tophat"
	mkdir -p $outdir/mapped/tophat
	mapper+=(tophat)
	cmd=()
	if [[ ! -e ${genome%.*}.1.bt2 ]]; then
		[[ $Smt -eq 0 ]] && /usr/bin/time -v ${BASH_ALIASES[bowtie2-build]} --threads $threads --seed 12345 $genome ${genome%.*} || echo "${BASH_ALIASES[bowtie2-build]} --threads $threads --seed 12345 $genome ${genome%.*}"
	fi
	for i in $(seq 0 $((${#fastq1[@]}-1))); do
		o=$outdir/mapped/tophat/$(basename ${fastq1[$i]})
		o=${o%.*}
		if [[ ${fastq2[0]} ]]; then #platypus dont like mapping ranges over c limits of short int (32767)
			cmd+=("${BASH_ALIASES[tophat2]} --max-intron-length 30000 --max-segment-intron 30000 --tmp-dir $outdir/tmp/tophat -p $threads -o $outdir/mapped/tophat ${genome%.*} ${fastq1[$i]} ${fastq2[$i]} && mv $outdir/mapped/tophat/accepted_hits.bam $o.unsorted && mv $outdir/mapped/tophat/unmapped.bam $o.unmapped.bam\n")
		else 
			cmd+=("${BASH_ALIASES[tophat2]} --max-intron-length 30000 --max-segment-intron 30000 --tmp-dir $outdir/tmp/tophat -p $threads -o $outdir/mapped/tophat ${genome%.*} ${fastq1[$i]} && mv $outdir/mapped/tophat/accepted_hits.bam $o.unsorted && mv $outdir/mapped/tophat/unmapped.bam $o.unmapped.bam\n")
		fi
		tophat+=($o.unsorted)
	done
	#enable dev skip option if already done
	[[ $Smt -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P 1 -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: tophat mapping failed"
		return 1
	fi
fi

	echo ":INFO: create sorted bams"
	cmd=()
	for r in ${mapper[@]}; do
		declare -n m=$r
		if [[ $r == 'tophat' ]]; then
			for i in $(seq 0 $((${#m[@]}-1))); do
				o=${m[$i]}
				o=${o%.*}
				cmd+=("${BASH_ALIASES[samtools]} sort $o.unsorted -T $o.tmp -o $o.bam\n")
				m[$i]=$o.bam
			done
		else 
			for i in $(seq 0 $((${#m[@]}-1))); do
				o=${m[$i]}
				o=${o%.*}
				cmd+=("${BASH_ALIASES[samtools]} view -bS $o.sam | ${BASH_ALIASES[samtools]} sort - -T $o.tmp -o $o.bam\n")
				m[$i]=$o.bam
			done
		fi
	done
	#enable dev skip option if already done
	[[ $Sort -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: sorting bam failed"
		return 1
	fi

	echo ":INFO: add read group information"
	cmd=()
	for r in ${mapper[@]}; do
		declare -n m=$r
		for f in ${m[@]}; do
			cmd+=("${BASH_ALIASES[picard]} AddOrReplaceReadGroups I=$f O=$f.tmp RGID=1 RGLB=lib1 RGPL=illumina RGPU=unit1 RGSM=sample VALIDATION_STRINGENCY=SILENT && mv $f.tmp $f\n")
		done
	done
	#enable dev skip option if already done
	[[ $Srg -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: read group modification failed"
		return 1
	fi

	echo ":INFO: index bam"
	cmd=()
	for r in ${mapper[@]}; do
		declare -n m=$r
		for f in ${m[@]}; do
			cmd+=("${BASH_ALIASES[samtools]} index $f\n")
		done
	done
	#enable dev skip option if already done
	[[ $Srg -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: indexing bam failed"
		return 1
	fi

	echo ":INFO: remove duplicates"
	cmd=()
	for r in ${mapper[@]}; do
		od=$outdir/noduplicates/$r
		mkdir -p $od
		declare -n m=$r
		for i in $(seq 0 $((${#m[@]}-1))); do
			o=$od/$(basename ${m[$i]})
			cmd+=("${BASH_ALIASES[picard]} MarkDuplicates I=${m[$i]} O=$o M=$o.metrics ASSUME_SORT_ORDER=coordinate VALIDATION_STRINGENCY=SILENT\n")
			m[$i]=$o
		done
	done
	#enable dev skip option if already done
	[[ $Srmd -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: duplicate removal failed"
		return 1
	fi

	echo ":INFO: index bam"
	cmd=()
	for r in ${mapper[@]}; do
		declare -n m=$r
		for f in ${m[@]}; do
			cmd+=("${BASH_ALIASES[samtools]} index $f\n")
		done
	done 
	#enable dev skip option if already done
	[[ $Srmd -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: indexing bam failed"
		return 1
	fi

	echo ":INFO: reorder bam"
	if [[ ! -e ${genome%.*}.dict ]]; then
		/usr/bin/time -v ${BASH_ALIASES[picard]} CreateSequenceDictionary R=$genome
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: genome dictionary creation failed"
			return 1
		fi
	fi
	if [[ ! -e $genome.fai ]]; then
		/usr/bin/time -v ${BASH_ALIASES[samtools]} faidx $genome
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: genome indexing failed"
			return 1
		fi
	fi
	cmd=()
	for r in ${mapper[@]}; do
		declare -n m=$r
		for i in $(seq 0 $((${#m[@]}-1))); do
			o=${m[$i]}
			o=${o%.*}
			cmd+=("${BASH_ALIASES[picard]} ReorderSam I=$o.bam O=$o.reordered.bam R=$genome CREATE_INDEX=TRUE VALIDATION_STRINGENCY=SILENT\n")
			m[$i]=$o.reordered.bam
		done
	done
	#enable dev skip option if already done
	[[ $Sreo -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: bam reordering failed"
		return 1
	fi

if [[ $norecal -eq 0 ]]; then
	echo ":INFO: indel error prediction"
	cmd=()
	for r in ${mapper[@]}; do
		od=$outdir/errorcorrected/$r
		mkdir -p $od
		declare -n m=$r
		for f in ${m[@]}; do
			o=$(basename $f)
			o=$od/${o%.*}.intervals
			cmd+=("${BASH_ALIASES[gatk]} -T RealignerTargetCreator -nt $threads -R $genome -I $f -o $o -U ALLOW_N_CIGAR_READS\n")
		done
	done
	#enable dev skip option if already done
	[[ $Sret -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P 1 -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: indel error prediction failed"
		return 1
	fi

	echo ":INFO: indel error correction"
	cmd=()
	for r in ${mapper[@]}; do
		od=$outdir/errorcorrected/$r
		declare -n m=$r
		for f in ${m[@]}; do
			o=$(basename $f)
			o=$od/${o%.*}
			cmd+=("${BASH_ALIASES[gatk]} -T IndelRealigner -R $genome -targetIntervals $o.intervals -I $f -o $o.torecal.bam -U ALLOW_N_CIGAR_READS\n")
		done
	done
	#enable dev skip option if already done
	[[ $Srea -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: indel error correction failed"
		return 1
	fi

	echo ":INFO: base recalibration"
	cmd=()
	for r in ${mapper[@]}; do
		od=$outdir/errorcorrected/$r
		declare -n m=$r
		for f in ${m[@]}; do
			o=$(basename $f)
			o=$od/${o%.*}
			cmd+=("${BASH_ALIASES[gatk]} -T BaseRecalibrator -nct $threads -R $genome -knownSites $genome.vcf -I $o.torecal.bam -o $o.recalreport -U ALLOW_N_CIGAR_READS\n")
		done
	done
	#enable dev skip option if already done
	[[ $Srec -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P 1 -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: base recalibration failed"
		return 1
	fi

	cmd=()
	for r in ${mapper[@]}; do
		od=$outdir/errorcorrected/$r
		declare -n m=$r
		for i in $(seq 0 $((${#m[@]}-1))); do
			o=$(basename ${m[$i]})
			o=$od/${o%.*}
			cmd+=("${BASH_ALIASES[gatk]} -T PrintReads -nct $threads -R $genome -I $o.torecal.bam -BQSR $o.recalreport -o $o.bam -U ALLOW_N_CIGAR_READS\n")
			m[$i]=$o.bam
		done
	done
	#enable dev skip option if already done
	[[ $Sprint -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P 1 -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: BQSR failed"
		return 1
	fi
fi

if [[ $nohc -eq 0 ]]; then
	echo ":INFO: variant calling - haplotypecaller"
	cmd=()
	for r in ${mapper[@]}; do
		od=$outdir/vcf/$r
		mkdir -p $od
		declare -n m=$r
		for f in ${m[@]}; do
			o=$(basename $f)
			o=$od/${o%.*}.haplotypecaller.vcf
			cmd+=("${BASH_ALIASES[gatk]} -T HaplotypeCaller -dt NONE -baq OFF --min_base_quality_score 0 --max_alternate_alleles 3 --useNewAFCalculator -nct $threads -R $genome -I $f --dbsnp $genome.vcf -U ALLOW_N_CIGAR_READS | ${BASH_ALIASES[bcftools]} view -Ou - | ${BASH_ALIASES[bcftools]} norm -f $genome -c s -m-both | ${BASH_ALIASES[vcfix]} > $o\n")
		done
	done
	#enable dev skip option if already done
	[[ $Shc -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P 1 -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: haplotypecaller failed"
		return 1
	fi
fi

if [[ $nomu -eq 0 ]]; then
	echo ":INFO: variant calling - mutect2"
	cmd=()
	for r in ${mapper[@]}; do
		od=$outdir/vcf/$r
		mkdir -p $od
		declare -n m=$r
		for f in ${m[@]}; do
			o=$(basename $f)
			o=$od/${o%.*}.mutect2.vcf
			cmd+=("${BASH_ALIASES[gatk]} -T MuTect2 -dt NONE -baq OFF --min_base_quality_score 0 --max_alternate_alleles 3 --useNewAFCalculator -nct $threads -R $genome -I:tumor $f --artifact_detection_mode --dbsnp $genome.vcf -U ALLOW_N_CIGAR_READS | ${BASH_ALIASES[bcftools]} view -Ou - | ${BASH_ALIASES[bcftools]} norm -f $genome -c s -m-both | ${BASH_ALIASES[vcfix]} > $o\n")
		done
	done
	#enable dev skip option if already done
	[[ $Smu -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P 1 -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: mutect failed"
		return 1
	fi
fi

if [[ $nofb -eq 0 ]]; then 
	echo ":INFO: variant calling - freebayes"
	cmd=()
	for r in ${mapper[@]}; do
		od=$outdir/tmp/$r
		mkdir -p $od
		declare -n m=$r
		for f in ${m[@]}; do
			o=$(basename $f)
			o=$od/${o%.*}.freebayes.vcf
			i=0
			for chr in $(${BASH_ALIASES[samtools]} view -H $f | grep '^@SQ' | perl -lane '$F[1]=~/SN:(.+)$/; $chr=$1; $F[2]=~/(\d+)$/; $l=$1; $chunk=sprintf("%d",$l/$ENV{threads}); $i=1; while(($i+1)*$chunk<$l){print($chr.":".($i*$chunk-$chunk+1)."-".($i*$chunk)); $i++} print($chr.":".(($i-1)*$chunk+1)."-".$l)'); do
				i=$((i+1))
				cmd+=("${BASH_ALIASES[freebayes]} -f $genome -r $chr --genotype-qualities --use-best-n-alleles 3 --min-coverage 10 --min-alternate-fraction 0.1 --use-mapping-quality --harmonic-indel-quality -P 0.0001 $f | ${BASH_ALIASES[bcftools]} view -Ou - | ${BASH_ALIASES[bcftools]} norm -f $genome -c s -m-both | ${BASH_ALIASES[vcfix]} > $o.$i\n")
			done
		done
	done
	#enable dev skip option if already done
	[[ $Sfb -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: freebayes failed"
		return 1
	fi

	if [[ $Sfb -eq 0 ]]; then
		for r in ${mapper[@]}; do
			tmpd=$outdir/tmp/$r
			od=$outdir/vcf/$r
			mkdir -p $od
			declare -n m=$r
			for f in ${m[@]}; do
				o=$(basename $f)
				tmp=$tmpd/${o%.*}.freebayes.vcf
				o=$od/${o%.*}.freebayes.vcf
				${BASH_ALIASES[bcftools]} view -h $tmp.1 > $o
				if [[ $? -gt 0 ]]; then
					echo ":ERROR: freebayes merge for $r failed"
					return 1
				fi
				cat $(ls -v $tmp.*) | awk '!/^#/{print}' >> $o
			done
		done
	fi
fi

if [[ $nost -eq 0 ]]; then
	echo ":INFO: variant calling - samtools"
	cmd=()
	for r in ${mapper[@]}; do
		od=$outdir/tmp/$r
		mkdir -p $od
		declare -n m=$r
		for f in ${m[@]}; do
			o=$(basename $f)
			o=$od/${o%.*}.samtools.vcf
			i=0
			for chr in $(${BASH_ALIASES[samtools]} view -H $f | grep '^@SQ' | perl -lane '$F[1]=~/SN:(.+)$/; $chr=$1; $F[2]=~/(\d+)$/; $l=$1; $chunk=sprintf("%d",$l/$ENV{threads}); $i=1; while(($i+1)*$chunk<$l){print($chr.":".($i*$chunk-$chunk+1)."-".($i*$chunk)); $i++} print($chr.":".(($i-1)*$chunk+1)."-".$l)'); do
				i=$((i+1))
				cmd+=("${BASH_ALIASES[samtools]} mpileup -u -v -t 'DP,AD,ADF,ADR,SP,INFO/AD,INFO/ADF,INFO/ADR' -m 10 -C 0 -B -Q 0 -d 100000 -L 100000 -f $genome -r $chr $f | ${BASH_ALIASES[bcftools]} call -Ou -m -f GQ,GP -v - | ${BASH_ALIASES[bcftools]} norm -f $genome -c s -m-both | ${BASH_ALIASES[vcfix]} > $o.$i\n")
			done
		done
	done
	#enable dev skip option if already done
	[[ $Sst -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: samtools failed"
		return 1
	fi

	if [[ $Sst -eq 0 ]]; then
		for r in ${mapper[@]}; do
			tmpd=$outdir/tmp/$r
			od=$outdir/vcf/$r
			mkdir -p $od
			declare -n m=$r
			for f in ${m[@]}; do
				o=$(basename $f)
				tmp=$tmpd/${o%.*}.samtools.vcf
				o=$od/${o%.*}.samtools.vcf
				${BASH_ALIASES[bcftools]} view -h $tmp.1 > $o
				if [[ $? -gt 0 ]]; then
					echo ":ERROR: samtools merge for $r failed"
					return 1
				fi
				cat $(ls -v $tmp.*) | awk '!/^#/{print}' >> $o
			done
		done
	fi
fi

if [[ $nopp -eq 0 ]]; then
	echo ":INFO: variant calling - platypus"
	cmd=()
	for r in ${mapper[@]}; do
		od=$outdir/tmp/$r
		mkdir -p $od
		declare -n m=$r
		for f in ${m[@]}; do
			o=$(basename $f)
			o=$od/${o%.*}.platypus.vcf
			cmd+=("${BASH_ALIASES[platypus]} callVariants --logFileName=$o.log --output=$o --refFile=$genome --bamFiles=$f --qdThreshold=0 --minGoodQualBases=0 --minBaseQual=0 --minMapQual=0 --minReads=10 --nCPU=$threads --filterVarsByCoverage=1 --minVarFreq=0.1 --filterDuplicates=1 --rmsmqThreshold=0 --qdThreshold=0 --useEMLikelihoods=1 --hapScoreThreshold=0 --badReadsThreshold=0 --maxVariants 100000 --minPosterior=3\n")			
		done
	done
	#enable dev skip option if already done
	[[ $Spp -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P 1 -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: platypus failed"
		return 1
	fi

	if [[ $Spp -eq 0 ]]; then
		cmd=()
		for r in ${mapper[@]}; do
			tmpd=$outdir/tmp/$r
			od=$outdir/vcf/$r
			mkdir -p $od
			declare -n m=$r
			for f in ${m[@]}; do
				o=$(basename $f)
				tmp=$tmpd/${o%.*}.platypus.vcf
				o=$od/${o%.*}.platypus.vcf
				${BASH_ALIASES[bgzip]} -f -@ $threads < $tmp > $tmp.gz
				if [[ $? -gt 0 ]]; then
					echo ":ERROR: platypus fix for $r failed"
					return 1
				fi
				${BASH_ALIASES[tabix]} -f -p vcf $tmp.gz
				cmd+=("${BASH_ALIASES[bcftools]} norm -f $genome -c s -m-both $tmp.gz | ${BASH_ALIASES[vcfix]} > $o\n")
			done
		done
		echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {}
		if [[ $? -gt 0 ]]; then
			echo ":ERROR: platypus fix failed"
			return 1
		fi
	fi
fi

if [[ $Smerge -eq 0 ]]; then	
	echo ":INFO: merging vcf files"
	cmd=()
	for r in ${mapper[@]}; do
		od=$outdir/vcf/$r
		declare -n m=$r
		for f in ${m[@]}; do
			o=$(basename $f)
			o=$od/${o%.*}
			for v in $(ls $o*.vcf | grep -v merged); do
				${BASH_ALIASES[bgzip]} -f -@ $threads < $v > $v.gz
				if [[ $? -gt 0 ]]; then
					echo ":ERROR: vcf compression for $r failed"
					return 1
				fi
				${BASH_ALIASES[tabix]} -f -p vcf $v.gz
			done
			if [[ $(ls $o*.vcf.gz | grep -v merged | wc -l) -gt 0 ]]; then
				${BASH_ALIASES[bcftools]} merge --print-header --force-samples $(ls $o*.vcf.gz | grep -v merged) > $o.merged.vcf
				if [[ $? -gt 0 ]]; then
					echo ":ERROR: vcf header merge for $r failed"
					return 1
				fi
				sed -i '$ d' $o.merged.vcf
				${BASH_ALIASES[vcfmerge]} $(ls $o*.vcf | grep -v merged) $(ls $o*.vcf | grep -v merged | perl -F'\.' -ane '{print $F[-2]." "}') >> $o.merged.vcf
				if [[ $? -gt 0 ]]; then
					echo ":ERROR: vcf merge failed"
					return 1
				fi
			fi
		done
	done

	for r in ${mapper[@]}; do
		od=$outdir/vcf/$r
		declare -n m=$r
		for f in ${m[@]}; do
			o=$(basename $f)
			o=$od/${o%.*}
			export caller=$(ls $o*.vcf | grep -v merged | head -1 | perl -F'\.' -ane '{print $F[-2]}')
			perl -lane '$F[7]=join(";",grep {$_=~s/^$ENV[caller]://; } split /;/,$F[7]); $F[7]="." unless $F[7]; print join "\t",@F' $o.merged.vcf > $o.merged.reduced.vcf
			if [[ $? -gt 0 ]]; then
				echo ":ERROR: vcf merge reduction for $r failed"
				return 1
			fi
			${BASH_ALIASES[bgzip]} -f -@ $threads < $o.merged.vcf > $o.merged.vcf.gz
			${BASH_ALIASES[tabix]} -f -p vcf $o.merged.vcf.gz
			${BASH_ALIASES[bgzip]} -f -@ $threads < $o.merged.reduced.vcf > $o.merged.reduced.vcf.gz
			${BASH_ALIASES[tabix]} -f -p vcf $o.merged.reduced.vcf.gz
		done
	done
fi

if [[ $noanno -eq 0 ]]; then
	if [[ $annovar -gt 0 ]]; then
		echo ":INFO: variant annotation - annovar"
		# ${BASH_ALIASES[convert2annovar]} -outfile $tooldir/annovar/example/ex2.avinput -format vcf4 -allsample -withfreq -includeinfo -comment -chrmt chrM $tooldir/annovar/example/ex2.vcf
		#g,g,r,r,f,f '-separate -exonicsplicing -hgvs','-separate -exonicsplicing -hgvs','','','','' ensGene,knownGene,cytoBand,genomicSuperDups,1000g2015aug_eur,snp142
		# ${BASH_ALIASES[annovar]} -thread $threads -maxgenethread $threads -csvout -outfile $tooldir/annovar/example/ex2.annotation -otherinfo -buildver hg19 -remove -nastring . -operation g,r,r,r,r,f,f,f,f,f,f -argument '-separate -exonicsplicing -hgvs','','','','','','','','','','' -protocol refGene,tfbsConsSites,wgRna,targetScanS,gwasCatalog,esp6500siv2_all,1000g2015aug_all,exac03,avsnp147,dbnsfp33a,clinvar_20170130 $tooldir/annovar/example/ex2.avinput $tooldir/annovar/humandb/
		for r in ${mapper[@]}; do
			id=$outdir/vcf/$r
			od=$outdir/annotation/$r/annovar
			mkdir -p $od
			declare -n m=$r
			for f in ${m[@]}; do
				i=$(basename $f)
				o=$od/${i%.*}
				i=$id/${i%.*}
				if [[ $Savar -eq 0 ]]; then
					/usr/bin/time -v ${BASH_ALIASES[tableannovar]} -thread $threads -maxgenethread $threads -vcfinput -tempdir $outdir/tmp -outfile $o -otherinfo -buildver hg19 -nastring . -operation g,r,r,r,r,f,f,f,f,f,f -argument '-separate -exonicsplicing -hgvs','','','','','','','','','','' -protocol refGene,tfbsConsSites,wgRna,targetScanS,gwasCatalog,esp6500siv2_all,1000g2015aug_all,exac03,avsnp147,dbnsfp33a,clinvar_20170130 $i.merged.reduced.vcf $tooldir/annovar/humandb/ 2>&1 | tee $outdir/tmp/annovarfiles
					if [[ $? -gt 0 ]]; then
						echo ":ERROR: annovar annotation for $r failed"
						return 1
					fi
                    for temp in $(grep -E 'written\s+to' $outdir/tmp/annovarfiles | grep -Eo "$outdir/tmp/[^[:space:],]+" | grep "temp."); do
                        ot=$(basename $temp)
                        ot=$o.${ot#*.}
                        mv $temp $ot
                    done
				else
					echo -e "${BASH_ALIASES[tableannovar]} -thread $threads -maxgenethread $threads -vcfinput -tempdir $outdir/tmp -outfile $o -otherinfo -buildver hg19 -nastring . -operation g,r,r,r,r,f,f,f,f,f,f -argument '-separate -exonicsplicing -hgvs','','','','','','','','','','' -protocol refGene,tfbsConsSites,wgRna,targetScanS,gwasCatalog,esp6500siv2_all,1000g2015aug_all,exac03,avsnp147,dbnsfp33a,clinvar_20170130 $i.merged.reduced.vcf $tooldir/annovar/humandb/\n"
				fi
			done
		done
	fi

	echo ":INFO: variant annotation - snpeff"
	cmd=()
	for r in ${mapper[@]}; do
		id=$outdir/vcf/$r
		od=$outdir/annotation/$r/snpeff
		mkdir -p $od
		declare -n m=$r
		for f in ${m[@]}; do
			i=$(basename $f)
			o=$od/${i%.*}
			i=$id/${i%.*}
			if [[ $Snpeff -eq 0 ]]; then
				/usr/bin/time -v ${BASH_ALIASES[snpeff]} ann -nodownload -v -t -lof GRCh37.75 $i.merged.reduced.vcf.gz > $o.annotated.vcf
				if [[ $? -gt 0 ]]; then
					echo ":ERROR: snpeff annotation for $r failed"
					return 1
				fi
			else
				echo -e "${BASH_ALIASES[snpeff]} ann -nodownload -v -t -lof GRCh37.75 $i.merged.reduced.vcf.gz > $o.annotated.vcf\n"
			fi
			cmd+=("${BASH_ALIASES[snpsift]} annotate -noDownload -v $tooldir/snpEff/data/clinvar.vcf.gz $o.annotated.vcf > $o.clinvar.vcf\n")
			cmd+=("${BASH_ALIASES[snpsift]} annotate -noDownload -v $genome.vcf.gz $o.annotated.vcf > $o.dbsnp.vcf\n")
			cmd+=("${BASH_ALIASES[snpsift]} annotate -noDownload  -v $tooldir/snpEff/data/exac.vcf.gz $o.annotated.vcf > $o.exac.vcf\n")
			cmd+=("${BASH_ALIASES[snpsift]} intervals -noDownload -v -i $o.annotated.vcf $tooldir/snpEff/data/promoter.bed > $o.promoter.vcf\n")
			cmd+=("${BASH_ALIASES[snpsift]} intervals -noDownload -v -i $o.annotated.vcf $tooldir/snpEff/data/miRNApromoter.bed > $o.miRNApromoter.vcf\n")
			cmd+=("${BASH_ALIASES[snpsift]} dbnsfp -noDownload -v -db $tooldir/snpEff/data/dbNSFP.txt.gz $o.annotated.vcf > $o.dbnsfp.vcf\n")
			cmd+=("${BASH_ALIASES[snpsift]} gwascat -noDownload -v -db $tooldir/snpEff/data/gwas.txt $o.annotated.vcf > $o.gwas.vcf\n")
		done
	done
	[[ $Snpeff -eq 0 ]] && echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {} || echo -e ${cmd[@]}
	if [[ $? -gt 0 ]]; then
		echo ":ERROR: snpsift failed"
		return 1
	fi

	# echo ":INFO: variant annotation - polyphen"
	# cmd=()
	# for i in $(seq 1 $threads); do 
	# 	cmd+=("${BASH_ALIASES[polyphen]} -r $i/$threads $PPH/sets/test.input > $outdir/tmp/test.polyphen.$i\n")
	# done
	# echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {}
	# if [[ $? -gt 0 ]]; then
	# 	echo ":ERROR: polyphen failed"
	# 	return 1
	# fi
	# cmd=()
	# for i in $(seq 1 $threads); do 
	# 	cmd+=("${BASH_ALIASES[weka]} -l $PPH/models/HumDiv.UniRef100.NBd.f11.model $outdir/tmp/test.polyphen.$i > $outdir/tmp/test.polyphenDiv.$i\n")
	# done
	# echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {}
	# if [[ $? -gt 0 ]]; then
	# 	echo ":ERROR: weka1 failed"
	# 	return 1
	# fi
	# cat $(ls -v $outdir/tmp/test.polyphenDiv.*) > $outdir/tmp/test.polyphenDiv
	# cmd=()
	# for i in $(seq 1 $threads); do 
	# 	cmd+=("${BASH_ALIASES[weka]} -l $PPH/models/HumVar.UniRef100.NBd.f11.model $outdir/tmp/test.polyphen.$i > $outdir/tmp/test.polyphenVar.$i\n")
	# done
	# echo -e ${cmd[@]} | /usr/bin/time -v xargs -P $threads -I {} bash -c {}
	# if [[ $? -gt 0 ]]; then
	# 	echo ":ERROR: weka2 failed"
	# 	return 1
	# fi
	# cat $(ls -v $outdir/tmp/test.polyphenVar.*) > $outdir/tmp/test.polyphenVar
fi

	echo ":INFO: fin"
	sleep 1
}

### main
pwd=$PWD
if [[ ! $MUVAC ]]; then
	echo ":ERROR: please do: export MUVAC=/full/path/to/requiered/tools"
	exit 1
fi
tooldir=$MUVAC
muvacdir=$(cd $(dirname $0) && echo $PWD && cd $pwd)
fq1=''
fq2=''
genome=''
threads=$( (sleep 1; echo 1) | script -e -q -c "stty rows 1000; top -n 2" /dev/null | grep -E 'Cpu[0-9]+' | awk '$3+$5<40{print}' | wc -l)
memory=$(script -e -q -c "stty rows 1000; top -b -n 1" /dev/null | grep 'KiB Mem' | perl -lane '$_=~/(\d+)\D+(\d+)\D+(\d+)/; printf("%d",($1-$3)/1024/1024)')
outdir=$pwd/results
help=0
verbose=0
make=''
noanno=0
adapter=''
nobmap=0
notmap=0
nosmap=0
norecal=0
nohc=0
nomu=0
nost=0
nofb=0
nopp=0
noprep=0
notrim=0
log=$outdir/run.log
remove=0
annovar=''
### dev opts
Sq=0
Sa=0
Scor=0
Sconv=0
Str=0
Sms=0
Smt=0
Smb=0
Sort=0
Srg=0
Srmd=0
Sreo=0
Sret=0
Srea=0
Srec=0
Sprint=0
Shc=0
Smu=0
Sfb=0
Sst=0
Spp=0
Smerge=0
split=0
Savar=0
Snpeff=0

checkopt (){
	opt=$1
	shift
	arg=$@
	case $opt in
	-h | --h | -help | --help) help=1; return 0;;
	-v | --v | -verbose | --verbose) verbose=1; return 0;;
	-no-anno | --no-annotation) noanno=1; return 0;;
	-no-bmap | --no-bwa) nobmap=1; return 0;;
	-no-tmap | --no-tophat) notmap=1; return 0;;
	-no-smap | --no-segemehl) nosmap=1; return 0;;
	-no-recal | --no-recalibration) norecal=1; return 0;;
	-no-hc | --no-haplotypecaller) nohc=1; return 0;;
	-no-mu | --no-mutect) nomu=1; return 0;;
	-no-st | --no-samtools) nost=1; return 0;;
	-no-fb | --no-freebayes) nofb=1; return 0;;
	-no-pp | --no-platypus) nopp=1; return 0;;
	-no-pre | --no-preprocessing) noprep=1; return 0;;
	-no-trim | --no-trimming) notrim=1; return 0;;
	-r | --r | -remove | --remove) remove=1; return 0;;
	-s | --s | -split | --split) split=1; return 0;;
	-Sq) Sq=1; return 0;;
	-Sa) Sa=1; return 0;;
	-Scor) Scor=1; return 0;;
	-Sconv) Sconv=1; return 0;;
	-Str) Str=1; return 0;;
	-Sms) Sms=1; return 0;;
	-Smt) Smt=1; return 0;;
	-Smb) Smb=1; return 0;;
	-Sort) Sort=1; return 0;;
	-Srg) Srg=1; return 0;;
	-Srmd) Srmd=1; return 0;;
	-Sreo) Sreo=1; return 0;;
	-Sret) Sret=1; return 0;;
	-Srea) Srea=1; return 0;;
	-Srec) Srec=1; return 0;;
	-Sprint) Sprint=1; return 0;;
	-Shc) Shc=1; return 0;;
	-Smu) Smu=1; return 0;;
	-Sfb) Sfb=1; return 0;;
	-Sst) Sst=1; return 0;;
	-Spp) Spp=1; return 0;;
	-Smerge) Smerge=1; return 0;;
	-Savar) Savar=1; return 0;;
	-Snpeff) Snpeff=1; return 0;;
	esac
	if [[ ! $arg =~ ^- ]]; then
		case $opt in
		-1 | --1 | -fastq1 | --fastq1) fq1=$arg;;
		-2 | --2 | -fastq2 | --fastq2) fq2=$arg;;
		-t | --t | -threads | --threads) threads=$arg;;
		-o | --o | -out | --out) outdir=$arg;;
		-g | --g | -genome | --genome) genome=$arg;;
		-a | --a | -adapter | --adapter) adapter=$arg;;
		-i | --i | -install | --install) make=$arg;;
		-l | --l | -log | --log) log=$arg;;
		-annovar | --annovar) annovar=$arg;;
		*$(basename $0)) echo "illegal option $arg"; exit 1;;
		-*) echo "illegal option $opt"; exit 1;; 
		*) echo "illegal option $arg"; exit 1;;
		esac
	else
		case $opt in
		-i | --i | -install | --install) make='all';;
		*) echo "illegal assignment $arg for option $opt"; exit 1;;
		esac
	fi
}
for i in $(seq 1 $#); do
	if [[ ${!i} =~ ^- ]]; then
		j=$((i+1))
		checkopt ${!i} ${!j}
	else 
		j=$((i-1))
		checkopt ${!j} ${!i}
	fi
done

if [[ $help -gt 0 ]]; then
	usage
fi

rundependencies
if [[ $? -gt 0 ]]; then
	exit 1
fi

if [[ $make ]]; then
    installdependencies
	echo ":INFO: installation started. please be patient. check logs via: tail -f $tooldir/install.log"
	echo '' > $tooldir/install.log
	if [[ $verbose -gt 0 ]]; then 
		install 2>&1 | tee $tooldir/install.log
		excode=${PIPESTATUS[0]}
	else
		progress &
		userlog $tooldir/install.log &
		install &>> $tooldir/install.log
		excode=${PIPESTATUS[0]}
	fi
	if [[ $excode -gt 0 ]]; then
		tail -1 $tooldir/install.log
		exit 1
	else 
		exit 0
	fi
fi

# alias definitions for system calls
tool=$(ls $tooldir/vcfix.pl)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i all"; exit 1; fi
alias vcfix=$tool

tool=$(ls $tooldir/vcfmerge.pl)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i all"; exit 1; fi
alias vcfmerge=$tool

tool=$(ls $tooldir/Trimmomatic-*/trimmomatic-*.jar | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i trimmomatic"; exit 1; fi
alias trimmomatic="java -Xmx${memory}g -Djava.io.tmpdir=$outdir/tmp -jar $tool"

tool=$(ls $tooldir/bcftools-*/bcftools | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i bcftools"; exit 1; fi
alias bcftools=$tool

tool=$(ls $tooldir/Rcorrector-*/run_rcorrector.pl | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i rcorrector"; exit 1; fi
alias rcorrector=$tool

tool=$(ls $tooldir/picard-*/picard.jar | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i picard"; exit 1; fi
alias picard="java -Xmx${memory}g -Djava.io.tmpdir=$outdir/tmp -jar $tool"

tool=$(ls $tooldir/freebayes/bin/freebayes | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i freebayes"; exit 1; fi
alias freebayes=$tool

tool=$tooldir/Platypus-master/bin/Platypus.py
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i platypus"; exit 1; fi
alias platypus=$tool

tool=$(ls $tooldir/fastx_toolkit-*/built/bin/fastq_quality_converter | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i fastx_toolkit"; exit 1; fi
alias fastq_quality_converter=$tool

tool=$(ls $tooldir/tophat-*/tophat2 | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i tophat"; exit 1; fi
alias tophat2=$tool

tool=$(ls $tooldir/bwa-*/bwa | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i bwa"; exit 1; fi
alias bwa=$tool

tool=$(ls $tooldir/gatk-*/target/executable/GenomeAnalysisTK.jar | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i gatk"; exit 1; fi
alias gatk="java -Xmx${memory}g -Djava.io.tmpdir=$outdir/tmp -jar $tool"

tool=$(ls $tooldir/bowtie2-*/bowtie2-build | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i tophat"; exit 1; fi
alias bowtie2-build=$tool

tool=$(ls $tooldir/segemehl_*/segemehl.x | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i segemehl"; exit 1; fi
alias segemehl=$tool

tool=$(ls $tooldir/samtools*/built/bin/samtools | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i samtools"; exit 1; fi
alias samtools=$tool

tool=$(ls $tooldir/samtools*/built/bin/tabix | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i samtools"; exit 1; fi
alias tabix=$tool

tool=$(ls $tooldir/samtools*/built/bin/bgzip | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i samtools"; exit 1; fi
alias bgzip=$tool

tool=$(ls $tooldir/FastQC-*/fastqc | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i fastqc"; exit 1; fi
alias fastqc=$tool

tool=$(ls $tooldir/DNApi-*/dnapi.py | sort -r | head -1)
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i dnapi"; exit 1; fi
alias dnapi=$tool

tool=$tooldir/cutadapt/bin/cutadapt
if [[ -z $tool ]]; then	echo ":ERROR: tool missing - try installation parameter: -i cutadapt"; exit 1; fi
alias cutadapt=$tool

annovar=1
tool=$tooldir/annovar/table_annovar.pl
if [[ -z $tool ]]; then	echo ":INFO: no annotation via annovar possible - try installation parameter: -i annovar -annovar <url>"; annovar=0; fi
alias tableannovar=$tool
alias convert2annovar=$tooldir/annovar/convert2annovar.pl

tool=$tooldir/snpEff/snpEff.jar
if [[ -z $tool ]]; then	echo ":INFO: no annotation via snpeff possible - try installation parameter: -i snpeff"; noanno=1; fi
alias snpeff="java -Xmx${memory}g -Djava.io.tmpdir=$outdir/tmp -jar $tool"
alias snpsift="java -Xmx${memory}g -Djava.io.tmpdir=$outdir/tmp -jar $tooldir/snpEff/SnpSift.jar"

# tool=$(ls $tooldir/polyphen-*/bin/run_pph.pl)
# if [[ -z $tool ]]; then	echo ":INFO: no annotation possible - try installation parameter: -i polyphen"; noanno=1; fi
# alias polyphen=$tool
# tool=$(ls $tooldir/polyphen-*/bin/run_weka.pl)
# alias weka=$tool
# export PERL5LIB=$tooldir/perl5/lib/perl5:$PERL5LIB
# export PPH=$(ls -d $tooldir/polyphen-*/ | sort -r | head -1)

export PYTHONPATH=$tooldir/cutadapt/lib/python2.7/site-packages:$PYTHONPATH
export threads
samtools=$(ls -dv $tooldir/samtools-*/ | tail -1)
export C_INCLUDE_PATH=$samtools/built/include:$C_INCLUDE_PATH
export LD_LIBRARY_PATH=$samtools/built/lib:$LD_LIBRARY_PATH

if [[ ! $genome ]] || [[ ! $fq1 ]]; then 
	echo ":ERROR: mandatory parameter missing - call "$(basename $0)" -h for help"
	exit 1
fi

cd $pwd
if [[ ! -e $genome ]]; then
	echo ":ERROR: genome file does not exists $genome"
	exit 1
fi
if [[ ! -e $genome.vcf ]]; then
	echo ":ERROR: dbSNP file does not exists $genome.vcf"
	exit 1
fi

declare -A fastq1
declare -A fastq2
IFS=','
i=-1
for f in $fq1; do
	if [[ ! -e $f ]]; then
		echo ":ERROR: fastq file does not exists $f"
		exit 1
	fi
	fastq1[$((i+1))]=$f
done
i=-1
for f in $fq2; do
	if [[ ! -e $f ]]; then
		echo ":ERROR: fastq file does not exists $f"
		exit 1
	fi
	fastq2[$((i+1))]=$f
done
unset IFS
if [[ $fq2 ]] && [[ ${#fastq1[@]} != ${#fastq2[@]} ]]; then 
	echo ":ERROR: fastq file of read paires missing"
	exit 1
fi

mkdir -p $outdir/tmp/segemehl
mkdir -p $outdir/tmp/tophat
mkdir -p $outdir/tmp/bwa

if [[ ! $adapter ]]; then
	echo -e ":INFO: no adapter provided! do you need to clip an adapter? [y|n]"
	read yn
	if [[ $yn =~ [yY] ]]; then
		echo ":INFO: suggesting adapter"
		a=$(${BASH_ALIASES[dnapi]} -k 6:10:2 --show-all ${fastq1[0]})
		b=$(${BASH_ALIASES[dnapi]} -k 6:10:2 --show-all ${fastq2[0]})
		echo -e "$a\n$b"
		exit 0
	fi
fi

echo ":INFO: pipeline started with $threads threads" | tee $log
echo ":INFO: command: "$(basename $0)" $@" | tee -a $log
echo ":INFO: check logs via tail -f $log"
if [[ $? -gt 0 ]]; then
	echo ":ERROR: directory for logfile does not exists $log"
	exit 1
fi
if [[ $verbose -gt 0 ]]; then 
	pipeline 2>&1 | tee -a $log
	excode=${PIPESTATUS[0]}
else
	progress &
	userlog $log &
	pipeline &>> $log
	excode=${PIPESTATUS[0]}
fi
if [[ $excode -gt 0 ]]; then
	tail -1 $log
	echo ":ERROR: pipeline failed" | tee -a $log
	exit 1
else 
	if [[ $remove -eq 1 ]]; then
		rm -rf $outdir/tmp
		ls $outdir/errorcorrected/*/* | grep -v -E 'reordered.(bam|bai)$' | xargs rm -f
		rm -rf $outdir/mapped/*/logs
		ls $outdir/mapped/*/* | grep -v -E '(bam|bai|unmapped.*)$' | xargs rm -f
		ls $outdir/noduplicates/*/* | grep -v -E 'reordered.(bam|bai)$' | xargs rm -f
		ls $outdir/rawcorrected/* | grep -E '(corrected|merged)$' | xargs rm -f
		rm -f log.txt
		rm -f *.bed
	fi
	exit 0
fi
